apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kubeapps.kubeappsapis.fullname" . }}-configmap
data:
  plugins.conf: |-
{{- if .Values.kubeappsapis.pluginConfig }}
{{ .Values.kubeappsapis.pluginConfig | toPrettyJson | indent 4 }}
{{- end }}
