apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubeapps.kubeappsapis.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: kubeappsapis
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.kubeappsapis.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.kubeappsapis.service.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.kubeappsapis.service.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.kubeappsapis.service.ports.http }}
      targetPort: grpc-http
      protocol: TCP
      name: grpc-http
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: kubeappsapis
