{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubeapps.kubeappsapis.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: kubeappsapis
  {{- if or .Values.kubeappsapis.service.annotations .Values.commonAnnotations }}
  {{- $annotations := merge .Values.kubeappsapis.service.annotations .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.kubeappsapis.service.ports.http }}
      targetPort: grpc-http
      protocol: TCP
      name: grpc-http
  {{- $podLabels := merge .Values.kubeappsapis.podLabels .Values.commonLabels }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: kubeappsapis
