{{- range .Values.apprepository.initialRepos }}
{{- if or .caCert .authorizationHeader .basicAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "apprepo-%s-secrets" .name }}
  {{- if .namespace }}
  namespace: {{ .namespace | quote }}
  {{- else }}
  namespace: {{ printf "%s%s" $.Release.Namespace $.Values.apprepository.globalReposNamespaceSuffix | quote }}
  {{- end }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    {{- if $.Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- if .caCert }}
  ca.crt: |-
    {{ .caCert | b64enc }}
  {{- end }}
  {{- $authorizationHeader := "" }}
  {{- if .authorizationHeader }}
    {{- $authorizationHeader = .authorizationHeader }}
  {{- else if .basicAuth }}
    {{- $authorizationHeader = printf "Basic %s" (printf "%s:%s" .basicAuth.user .basicAuth.password | b64enc) }}
  {{- end }}
  {{- if $authorizationHeader }}
  authorizationHeader: |-
    {{ $authorizationHeader | b64enc }}
  {{- end }}
---
{{/* credentials are required in the release namespace for syncer jobs */}}
{{- if or .namespace $.Values.apprepository.globalReposNamespaceSuffix }}
apiVersion: v1
kind: Secret
metadata:
  {{- if .namespace }}
  name: {{ printf "%s-apprepo-%s" .namespace .name }}
  {{- else }}
  name: {{ printf "%s%s-apprepo-%s" $.Release.Namespace $.Values.apprepository.globalReposNamespaceSuffix .name }}
  {{- end }}  
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    {{- if $.Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- if .caCert }}
  ca.crt: |-
    {{ .caCert | b64enc }}
  {{- end }}
  {{- if $authorizationHeader }}
  authorizationHeader: |-
    {{ $authorizationHeader | b64enc }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
