redis:
  enabled: true
  master: 
    extraFlags:
      ## Intentionally a small number to test scenarios where cache eviction policies kick in
      - "--maxmemory 10mb"
      - "--maxmemory-policy allkeys-lru"
  replica:
    extraFlags:
      ## Intentionally a small number to test scenarios where cache eviction policies kick in
      - "--maxmemory 10mb"
      - "--maxmemory-policy allkeys-lru"
