# Copyright 2022 the Kubeapps contributors.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ include "simplechart.fullname" . }}
  labels:
    {{- include "simplechart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "simplechart.selectorLabels" . | nindent 4 }}
