# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

---
extends: default
ignore: |
  */chart/kubeapps/templates/
  */integration/charts/simplechart/templates/
rules:
  line-length: disable
  comments: disable
