# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

---
extends: default
ignore: |
  **/chart/kubeapps/templates/
  **/charts/simplechart/templates/
  **/plugins/fluxv2/packages/v1alpha1/testdata/charts/single-package-template.yaml
rules:
  line-length: disable
  comments: disable
  trailing-spaces:
    level: warning
  truthy:
    check-keys: false
