[build]
publish = "public"
command = "hugo --gc --minify --enableGitInfo"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[context.production.environment]
HUGO_VERSION = "0.124.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.124.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL --enableGitInfo"

[context.deploy-preview.environment]
HUGO_VERSION = "0.124.1"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL --enableGitInfo"

[context.branch-deploy.environment]
HUGO_VERSION = "0.124.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "/*"
to = "/404/"
status = 404
