# Copyright 2018-2022 the Kubeapps contributors.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apprepositories.kubeapps.com
spec:
  group: kubeapps.com
  version: v1alpha1
  names:
    kind: AppRepository
    plural: apprepositories
    shortNames:
      - apprepos
  scope: Namespaced
