{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if gt (len .Values.clusters) 0 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kubeapps.clusters-config.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  clusters.conf: |-
{{ .Values.clusters | toPrettyJson | indent 4 }}
{{- end }}
