{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if or .Values.apprepository.globalReposNamespaceSuffix .Values.kubeappsapis.pluginConfig.helm.packages.v1alpha1.globalPackagingNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "kubeapps.helmGlobalPackagingNamespace" . | quote }}
{{- end }}
