# permissions for end users to view apprepositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apprepository-viewer-role
rules:
- apiGroups:
  - kubeapps.com
  resources:
  - apprepositories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeapps.com
  resources:
  - apprepositories/status
  verbs:
  - get
