# permissions for end users to edit apprepositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apprepository-editor-role
rules:
- apiGroups:
  - kubeapps.com
  resources:
  - apprepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeapps.com
  resources:
  - apprepositories/status
  verbs:
  - get
