---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kubeapps.com
  resources:
  - apprepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeapps.com
  resources:
  - apprepositories/finalizers
  verbs:
  - update
- apiGroups:
  - kubeapps.com
  resources:
  - apprepositories/status
  verbs:
  - get
  - patch
  - update
