# Copyright 2020-2022 the Kubeapps contributors.
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeapps-namespace-discovery
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
  - apiGroups:
      - "packages.operators.coreos.com/v1"
    resources:
      - packagemanifests
    verbs:
      - list
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeapps-namespace-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeapps-namespace-discovery
subjects:
  - kind: ServiceAccount
    name: kubeapps-namespace-discovery
    namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeapps-namespace-discovery
  namespace: default
secrets:
  - name: kubeapps-namespace-discovery
---
apiVersion: v1
kind: Secret
metadata:
  name: kubeapps-namespace-discovery
  namespace: default
  annotations:
    "kubernetes.io/service-account.name": kubeapps-namespace-discovery
type: "kubernetes.io/service-account-token"
