//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2022 the Kubeapps contributors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppRepository) DeepCopyInto(out *AppRepository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppRepository.
func (in *AppRepository) DeepCopy() *AppRepository {
	if in == nil {
		return nil
	}
	out := new(AppRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppRepository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppRepositoryAuth) DeepCopyInto(out *AppRepositoryAuth) {
	*out = *in
	if in.Header != nil {
		in, out := &in.Header, &out.Header
		*out = new(AppRepositoryAuthHeader)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomCA != nil {
		in, out := &in.CustomCA, &out.CustomCA
		*out = new(AppRepositoryCustomCA)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppRepositoryAuth.
func (in *AppRepositoryAuth) DeepCopy() *AppRepositoryAuth {
	if in == nil {
		return nil
	}
	out := new(AppRepositoryAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppRepositoryAuthHeader) DeepCopyInto(out *AppRepositoryAuthHeader) {
	*out = *in
	in.SecretKeyRef.DeepCopyInto(&out.SecretKeyRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppRepositoryAuthHeader.
func (in *AppRepositoryAuthHeader) DeepCopy() *AppRepositoryAuthHeader {
	if in == nil {
		return nil
	}
	out := new(AppRepositoryAuthHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppRepositoryCustomCA) DeepCopyInto(out *AppRepositoryCustomCA) {
	*out = *in
	in.SecretKeyRef.DeepCopyInto(&out.SecretKeyRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppRepositoryCustomCA.
func (in *AppRepositoryCustomCA) DeepCopy() *AppRepositoryCustomCA {
	if in == nil {
		return nil
	}
	out := new(AppRepositoryCustomCA)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppRepositoryList) DeepCopyInto(out *AppRepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AppRepository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppRepositoryList.
func (in *AppRepositoryList) DeepCopy() *AppRepositoryList {
	if in == nil {
		return nil
	}
	out := new(AppRepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppRepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppRepositorySpec) DeepCopyInto(out *AppRepositorySpec) {
	*out = *in
	in.Auth.DeepCopyInto(&out.Auth)
	if in.DockerRegistrySecrets != nil {
		in, out := &in.DockerRegistrySecrets, &out.DockerRegistrySecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OCIRepositories != nil {
		in, out := &in.OCIRepositories, &out.OCIRepositories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.FilterRule.DeepCopyInto(&out.FilterRule)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppRepositorySpec.
func (in *AppRepositorySpec) DeepCopy() *AppRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(AppRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppRepositoryStatus) DeepCopyInto(out *AppRepositoryStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Artifact != nil {
		in, out := &in.Artifact, &out.Artifact
		*out = new(Artifact)
		(*in).DeepCopyInto(*out)
	}
	out.ReconcileRequestStatus = in.ReconcileRequestStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppRepositoryStatus.
func (in *AppRepositoryStatus) DeepCopy() *AppRepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(AppRepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Artifact) DeepCopyInto(out *Artifact) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Artifact.
func (in *Artifact) DeepCopy() *Artifact {
	if in == nil {
		return nil
	}
	out := new(Artifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterRuleSpec) DeepCopyInto(out *FilterRuleSpec) {
	*out = *in
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterRuleSpec.
func (in *FilterRuleSpec) DeepCopy() *FilterRuleSpec {
	if in == nil {
		return nil
	}
	out := new(FilterRuleSpec)
	in.DeepCopyInto(out)
	return out
}
