# Copyright 2019-2022 the Kubeapps contributors.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: e2e-runner
  name: e2e-runner
spec:
  selector:
    matchLabels:
      run: e2e-runner
  template:
    metadata:
      labels:
        run: e2e-runner
    spec:
      containers:
        - args:
            - tail
            - -f
            - /dev/null
          image: kubeapps/integration-tests:v2.0.0
          name: integration
          # TODO (castelblanque) Adjust properly the resources.
          # Current values are not empirically demonstrated.
          resources:
            requests:
              memory: 300Mi
              cpu: 250m
            limits:
              memory: 600Mi
              cpu: 500m
