// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.15.2
// source: kubeappsapis/core/packagerepositories/v1/repositories.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A PackageRepository is identified by a name and optionally a specific namespace.
// TODO: this should be embedded in the AvailablePackage as it's just a reference
// to a repo, not an entity on its own.
type PackageRepository struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *PackageRepository) Reset() {
	*x = PackageRepository{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kubeappsapis_core_packagerepositories_v1_repositories_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackageRepository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageRepository) ProtoMessage() {}

func (x *PackageRepository) ProtoReflect() protoreflect.Message {
	mi := &file_kubeappsapis_core_packagerepositories_v1_repositories_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageRepository.ProtoReflect.Descriptor instead.
func (*PackageRepository) Descriptor() ([]byte, []int) {
	return file_kubeappsapis_core_packagerepositories_v1_repositories_proto_rawDescGZIP(), []int{0}
}

func (x *PackageRepository) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackageRepository) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// An AvailablePackage defines a package available for installation.
type AvailablePackage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the package.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The package repository where this package is located.
	Repository *PackageRepository `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	// The latest version of the package in the repository.
	LatestVersion string `protobuf:"bytes,3,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	// A url for an icon.
	IconUrl string `protobuf:"bytes,4,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
}

func (x *AvailablePackage) Reset() {
	*x = AvailablePackage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kubeappsapis_core_packagerepositories_v1_repositories_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvailablePackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailablePackage) ProtoMessage() {}

func (x *AvailablePackage) ProtoReflect() protoreflect.Message {
	mi := &file_kubeappsapis_core_packagerepositories_v1_repositories_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailablePackage.ProtoReflect.Descriptor instead.
func (*AvailablePackage) Descriptor() ([]byte, []int) {
	return file_kubeappsapis_core_packagerepositories_v1_repositories_proto_rawDescGZIP(), []int{1}
}

func (x *AvailablePackage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AvailablePackage) GetRepository() *PackageRepository {
	if x != nil {
		return x.Repository
	}
	return nil
}

func (x *AvailablePackage) GetLatestVersion() string {
	if x != nil {
		return x.LatestVersion
	}
	return ""
}

func (x *AvailablePackage) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

type GetAvailablePackagesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A cluster name can be provided otherwise the current cluster will be assumed.
	Cluster string `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// A namespace can be provided if the packages available for install in a
	// specific namespace are required.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *GetAvailablePackagesRequest) Reset() {
	*x = GetAvailablePackagesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kubeappsapis_core_packagerepositories_v1_repositories_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvailablePackagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailablePackagesRequest) ProtoMessage() {}

func (x *GetAvailablePackagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubeappsapis_core_packagerepositories_v1_repositories_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailablePackagesRequest.ProtoReflect.Descriptor instead.
func (*GetAvailablePackagesRequest) Descriptor() ([]byte, []int) {
	return file_kubeappsapis_core_packagerepositories_v1_repositories_proto_rawDescGZIP(), []int{2}
}

func (x *GetAvailablePackagesRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *GetAvailablePackagesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

var File_kubeappsapis_core_packagerepositories_v1_repositories_proto protoreflect.FileDescriptor

var file_kubeappsapis_core_packagerepositories_v1_repositories_proto_rawDesc = []byte{
	0x0a, 0x3b, 0x6b, 0x75, 0x62, 0x65, 0x61, 0x70, 0x70, 0x73, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x63,
	0x6f, 0x72, 0x65, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x72, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x28, 0x6b,
	0x75, 0x62, 0x65, 0x61, 0x70, 0x70, 0x73, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65,
	0x2e, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x45, 0x0a, 0x11, 0x50, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0xc5,
	0x01, 0x0a, 0x10, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x5b, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x6b, 0x75,
	0x62, 0x65, 0x61, 0x70, 0x70, 0x73, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72,
	0x69, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x0a, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x6f, 0x72, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x61,
	0x74, 0x65, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x69,
	0x63, 0x6f, 0x6e, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69,
	0x63, 0x6f, 0x6e, 0x55, 0x72, 0x6c, 0x22, 0x55, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12,
	0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x42, 0x60, 0x5a,
	0x5e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x75, 0x62, 0x65,
	0x61, 0x70, 0x70, 0x73, 0x2f, 0x6b, 0x75, 0x62, 0x65, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x63, 0x6d,
	0x64, 0x2f, 0x6b, 0x75, 0x62, 0x65, 0x61, 0x70, 0x70, 0x73, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6b, 0x75, 0x62, 0x65, 0x61, 0x70, 0x70, 0x73, 0x61,
	0x70, 0x69, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kubeappsapis_core_packagerepositories_v1_repositories_proto_rawDescOnce sync.Once
	file_kubeappsapis_core_packagerepositories_v1_repositories_proto_rawDescData = file_kubeappsapis_core_packagerepositories_v1_repositories_proto_rawDesc
)

func file_kubeappsapis_core_packagerepositories_v1_repositories_proto_rawDescGZIP() []byte {
	file_kubeappsapis_core_packagerepositories_v1_repositories_proto_rawDescOnce.Do(func() {
		file_kubeappsapis_core_packagerepositories_v1_repositories_proto_rawDescData = protoimpl.X.CompressGZIP(file_kubeappsapis_core_packagerepositories_v1_repositories_proto_rawDescData)
	})
	return file_kubeappsapis_core_packagerepositories_v1_repositories_proto_rawDescData
}

var file_kubeappsapis_core_packagerepositories_v1_repositories_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kubeappsapis_core_packagerepositories_v1_repositories_proto_goTypes = []interface{}{
	(*PackageRepository)(nil),           // 0: kubeappsapis.core.packagerepositories.v1.PackageRepository
	(*AvailablePackage)(nil),            // 1: kubeappsapis.core.packagerepositories.v1.AvailablePackage
	(*GetAvailablePackagesRequest)(nil), // 2: kubeappsapis.core.packagerepositories.v1.GetAvailablePackagesRequest
}
var file_kubeappsapis_core_packagerepositories_v1_repositories_proto_depIdxs = []int32{
	0, // 0: kubeappsapis.core.packagerepositories.v1.AvailablePackage.repository:type_name -> kubeappsapis.core.packagerepositories.v1.PackageRepository
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kubeappsapis_core_packagerepositories_v1_repositories_proto_init() }
func file_kubeappsapis_core_packagerepositories_v1_repositories_proto_init() {
	if File_kubeappsapis_core_packagerepositories_v1_repositories_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kubeappsapis_core_packagerepositories_v1_repositories_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackageRepository); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kubeappsapis_core_packagerepositories_v1_repositories_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvailablePackage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kubeappsapis_core_packagerepositories_v1_repositories_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAvailablePackagesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kubeappsapis_core_packagerepositories_v1_repositories_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kubeappsapis_core_packagerepositories_v1_repositories_proto_goTypes,
		DependencyIndexes: file_kubeappsapis_core_packagerepositories_v1_repositories_proto_depIdxs,
		MessageInfos:      file_kubeappsapis_core_packagerepositories_v1_repositories_proto_msgTypes,
	}.Build()
	File_kubeappsapis_core_packagerepositories_v1_repositories_proto = out.File
	file_kubeappsapis_core_packagerepositories_v1_repositories_proto_rawDesc = nil
	file_kubeappsapis_core_packagerepositories_v1_repositories_proto_goTypes = nil
	file_kubeappsapis_core_packagerepositories_v1_repositories_proto_depIdxs = nil
}
