// Copyright 2020-2022 the Kubeapps contributors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AppRepositoryListerExpansion allows custom methods to be added to
// AppRepositoryLister.
type AppRepositoryListerExpansion interface{}

// AppRepositoryNamespaceListerExpansion allows custom methods to be added to
// AppRepositoryNamespaceLister.
type AppRepositoryNamespaceListerExpansion interface{}
