// Copyright 2020-2022 the Kubeapps contributors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/kubeapps/cmd/apprepository-controller/pkg/client/clientset/versioned/typed/apprepository/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeKubeappsV1alpha1 struct {
	*testing.Fake
}

func (c *FakeKubeappsV1alpha1) AppRepositories(namespace string) v1alpha1.AppRepositoryInterface {
	return &FakeAppRepositories{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeKubeappsV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
