// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.15.2
// source: kubeappsapis/core/packages/v1/packages.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A PackageRepository is identified by a name and optionally a specific namespace.
type InstalledPackageSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Version   string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	IconUrl   string `protobuf:"bytes,4,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
}

func (x *InstalledPackageSummary) Reset() {
	*x = InstalledPackageSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kubeappsapis_core_packages_v1_packages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstalledPackageSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstalledPackageSummary) ProtoMessage() {}

func (x *InstalledPackageSummary) ProtoReflect() protoreflect.Message {
	mi := &file_kubeappsapis_core_packages_v1_packages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstalledPackageSummary.ProtoReflect.Descriptor instead.
func (*InstalledPackageSummary) Descriptor() ([]byte, []int) {
	return file_kubeappsapis_core_packages_v1_packages_proto_rawDescGZIP(), []int{0}
}

func (x *InstalledPackageSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstalledPackageSummary) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *InstalledPackageSummary) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstalledPackageSummary) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

// Get installed packages within a namespace or on the cluster (if RBAC allows)
type GetInstalledPackagesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *GetInstalledPackagesRequest) Reset() {
	*x = GetInstalledPackagesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kubeappsapis_core_packages_v1_packages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInstalledPackagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstalledPackagesRequest) ProtoMessage() {}

func (x *GetInstalledPackagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubeappsapis_core_packages_v1_packages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstalledPackagesRequest.ProtoReflect.Descriptor instead.
func (*GetInstalledPackagesRequest) Descriptor() ([]byte, []int) {
	return file_kubeappsapis_core_packages_v1_packages_proto_rawDescGZIP(), []int{1}
}

func (x *GetInstalledPackagesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

var File_kubeappsapis_core_packages_v1_packages_proto protoreflect.FileDescriptor

var file_kubeappsapis_core_packages_v1_packages_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x6b, 0x75, 0x62, 0x65, 0x61, 0x70, 0x70, 0x73, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x63,
	0x6f, 0x72, 0x65, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f,
	0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d,
	0x6b, 0x75, 0x62, 0x65, 0x61, 0x70, 0x70, 0x73, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x80, 0x01,
	0x0a, 0x17, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x63, 0x6f, 0x6e, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x63, 0x6f, 0x6e, 0x55, 0x72, 0x6c,
	0x22, 0x3b, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64,
	0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x42, 0x55, 0x5a,
	0x53, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x75, 0x62, 0x65,
	0x61, 0x70, 0x70, 0x73, 0x2f, 0x6b, 0x75, 0x62, 0x65, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x63, 0x6d,
	0x64, 0x2f, 0x6b, 0x75, 0x62, 0x65, 0x61, 0x70, 0x70, 0x73, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6b, 0x75, 0x62, 0x65, 0x61, 0x70, 0x70, 0x73, 0x61,
	0x70, 0x69, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x73, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kubeappsapis_core_packages_v1_packages_proto_rawDescOnce sync.Once
	file_kubeappsapis_core_packages_v1_packages_proto_rawDescData = file_kubeappsapis_core_packages_v1_packages_proto_rawDesc
)

func file_kubeappsapis_core_packages_v1_packages_proto_rawDescGZIP() []byte {
	file_kubeappsapis_core_packages_v1_packages_proto_rawDescOnce.Do(func() {
		file_kubeappsapis_core_packages_v1_packages_proto_rawDescData = protoimpl.X.CompressGZIP(file_kubeappsapis_core_packages_v1_packages_proto_rawDescData)
	})
	return file_kubeappsapis_core_packages_v1_packages_proto_rawDescData
}

var file_kubeappsapis_core_packages_v1_packages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kubeappsapis_core_packages_v1_packages_proto_goTypes = []interface{}{
	(*InstalledPackageSummary)(nil),     // 0: kubeappsapis.core.packages.v1.InstalledPackageSummary
	(*GetInstalledPackagesRequest)(nil), // 1: kubeappsapis.core.packages.v1.GetInstalledPackagesRequest
}
var file_kubeappsapis_core_packages_v1_packages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kubeappsapis_core_packages_v1_packages_proto_init() }
func file_kubeappsapis_core_packages_v1_packages_proto_init() {
	if File_kubeappsapis_core_packages_v1_packages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kubeappsapis_core_packages_v1_packages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstalledPackageSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kubeappsapis_core_packages_v1_packages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInstalledPackagesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kubeappsapis_core_packages_v1_packages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kubeappsapis_core_packages_v1_packages_proto_goTypes,
		DependencyIndexes: file_kubeappsapis_core_packages_v1_packages_proto_depIdxs,
		MessageInfos:      file_kubeappsapis_core_packages_v1_packages_proto_msgTypes,
	}.Build()
	File_kubeappsapis_core_packages_v1_packages_proto = out.File
	file_kubeappsapis_core_packages_v1_packages_proto_rawDesc = nil
	file_kubeappsapis_core_packages_v1_packages_proto_goTypes = nil
	file_kubeappsapis_core_packages_v1_packages_proto_depIdxs = nil
}
