# Copyright 2022 the Kubeapps contributors
# SPDX-License-Identifier: Apache-2.0

---
name: Full Integration Pipeline

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.ref_name }}_full
  cancel-in-progress: true

jobs:
  CI:
    uses: ./.github/workflows/kubeapps-general.yaml
    secrets: inherit
    with:
      run_gke_tests: true
      run_linters: false
