// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	v1 "github.com/kubeapps/kubeapps/cmd/kubeapps-api-service/kubeappsapis/core/packagerepositories/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PackageRepositoriesServiceClient is the client API for PackageRepositoriesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PackageRepositoriesServiceClient interface {
	GetAvailablePackages(ctx context.Context, in *v1.GetAvailablePackagesRequest, opts ...grpc.CallOption) (PackageRepositoriesService_GetAvailablePackagesClient, error)
}

type packageRepositoriesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPackageRepositoriesServiceClient(cc grpc.ClientConnInterface) PackageRepositoriesServiceClient {
	return &packageRepositoriesServiceClient{cc}
}

func (c *packageRepositoriesServiceClient) GetAvailablePackages(ctx context.Context, in *v1.GetAvailablePackagesRequest, opts ...grpc.CallOption) (PackageRepositoriesService_GetAvailablePackagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &PackageRepositoriesService_ServiceDesc.Streams[0], "/kubeappsapis.plugins.packagerepositories.kapp_controller.v1.PackageRepositoriesService/GetAvailablePackages", opts...)
	if err != nil {
		return nil, err
	}
	x := &packageRepositoriesServiceGetAvailablePackagesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PackageRepositoriesService_GetAvailablePackagesClient interface {
	Recv() (*v1.AvailablePackage, error)
	grpc.ClientStream
}

type packageRepositoriesServiceGetAvailablePackagesClient struct {
	grpc.ClientStream
}

func (x *packageRepositoriesServiceGetAvailablePackagesClient) Recv() (*v1.AvailablePackage, error) {
	m := new(v1.AvailablePackage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PackageRepositoriesServiceServer is the server API for PackageRepositoriesService service.
// All implementations must embed UnimplementedPackageRepositoriesServiceServer
// for forward compatibility
type PackageRepositoriesServiceServer interface {
	GetAvailablePackages(*v1.GetAvailablePackagesRequest, PackageRepositoriesService_GetAvailablePackagesServer) error
	mustEmbedUnimplementedPackageRepositoriesServiceServer()
}

// UnimplementedPackageRepositoriesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPackageRepositoriesServiceServer struct {
}

func (UnimplementedPackageRepositoriesServiceServer) GetAvailablePackages(*v1.GetAvailablePackagesRequest, PackageRepositoriesService_GetAvailablePackagesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAvailablePackages not implemented")
}
func (UnimplementedPackageRepositoriesServiceServer) mustEmbedUnimplementedPackageRepositoriesServiceServer() {
}

// UnsafePackageRepositoriesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PackageRepositoriesServiceServer will
// result in compilation errors.
type UnsafePackageRepositoriesServiceServer interface {
	mustEmbedUnimplementedPackageRepositoriesServiceServer()
}

func RegisterPackageRepositoriesServiceServer(s grpc.ServiceRegistrar, srv PackageRepositoriesServiceServer) {
	s.RegisterService(&PackageRepositoriesService_ServiceDesc, srv)
}

func _PackageRepositoriesService_GetAvailablePackages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(v1.GetAvailablePackagesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PackageRepositoriesServiceServer).GetAvailablePackages(m, &packageRepositoriesServiceGetAvailablePackagesServer{stream})
}

type PackageRepositoriesService_GetAvailablePackagesServer interface {
	Send(*v1.AvailablePackage) error
	grpc.ServerStream
}

type packageRepositoriesServiceGetAvailablePackagesServer struct {
	grpc.ServerStream
}

func (x *packageRepositoriesServiceGetAvailablePackagesServer) Send(m *v1.AvailablePackage) error {
	return x.ServerStream.SendMsg(m)
}

// PackageRepositoriesService_ServiceDesc is the grpc.ServiceDesc for PackageRepositoriesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PackageRepositoriesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kubeappsapis.plugins.packagerepositories.kapp_controller.v1.PackageRepositoriesService",
	HandlerType: (*PackageRepositoriesServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAvailablePackages",
			Handler:       _PackageRepositoriesService_GetAvailablePackages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kubeappsapis/plugins/packagerepositories/kapp_controller/v1/kapp_conttroller.proto",
}
